name: Build and upload reports

on:
  schedule:
    - cron: '0 12 * * *'  # daily at 12:00 UTC
  workflow_dispatch:

jobs:
  build-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install UV (optional)
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "${HOME}/.cargo/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate report
        run: |
          python run_prop_update.py || true
          python enhanced_visualizer.py || true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/**
